### ISSUE TITLE
Contribute Page

### ISSUE THREAD

**Issue by bcomnes** [CodeForPortland/codeforportland.github.io#26]
We need a page about how people can contribute.  Some topics for this page:
- How to contribute to the website
- How to sponsor meetups or contribute resources
- How to reach out with data or other information

**Comment by ngoldman** [comment]
I think we can add a CONTRIBUTING.md file in the vein of https://github.com/jden/CONTRIBUTING.md/blob/master/CONTRIBUTING.md and make it a page on the site as well.

**Comment by bcomnes** [comment]
:+1:
