### ISSUE TITLE
Projects List/Page

### ISSUE THREAD

**Issue by bcomnes** [CodeForPortland/codeforportland.github.io#27]
We need a page talking about notable projects.

**Comment by ngoldman** [comment]
I retired the `CodeForPortland/projects` repo in favor of keeping projects info in a projects folder in this repo. Working on improving this repo in general.

**Comment by bcomnes** [comment]
Looks good @ngoldman I really dropped the ball on this

**Comment by ngoldman** [comment]
@bcomnes no worries it's a group effort and we've had 100 other things happen since this
