### ISSUE TITLE
Explore a simpler site theme

### ISSUE THREAD

**Issue by bcomnes** [CodeForPortland/codeforportland.github.io#39]
We worked on testing out a simpler website theme, and ngoldman has some pretty cool ideas about a modular gh-page system (@ngoldman can you post a scan of that whiteboard?).

I started testing out the site content with mdo's [hyde](http://andhyde.com) template.  It's not ready by any means, but gives an idea of a simplified template for the site.  This experiment lives in my "fresh" branch:  https://github.com/bcomnes/codeforportland.github.io/tree/fresh  It can be tested with only jekyll installed.

**Comment by ungoldman** [comment]
✅  mission accomplished
