### ISSUE TITLE
Switch to CC0 license

### ISSUE THREAD

**Issue by ngoldman** [CodeForPortland/codeforportland.github.io#46]
@fardog if it's alright with you I'd like to switch this project's license from MIT to [CC0](https://creativecommons.org/publicdomain/zero/1.0/). The copyright is currently under your name so I want to check with you first before I make the change. :grin:

**Comment by fardog** [comment]
@ngoldman Yep, no problem.

**Comment by fardog** [comment]
@ngoldman also, feel free to change the copyright to Code for Portland or whatever makes sense.

**Comment by ngoldman** [comment]
@fardog Thanks! I think I will switch source code to CC0 (public domain) to make it clear anyone can use it for anything without attribution necessary, but will keep content as CC BY 3.0 to ensure any content made by contributors is theirs. Does that make sense?

**Comment by fardog** [comment]
:+1:

**Comment by ngoldman** [comment]
meh
